on:
  schedule:
    - cron: "00 12 1 * *"
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch URL
        uses: boyeborg/fetch-url-action@v1.1
        with: 
          url: "https://parceiros.coclima.com/api/asaas/createCharge?token=coClima2022"


